creating `README.md`
lilhind/bookipedia pull request #2
Opened 2024-01-07 18:28 UTC by lilhind

adding project info

2024-01-07 20:27 UTC, mhmadalaa requested changes
Just give a hint that it's the backend part not the all project

2024-01-08 11:42 UTC, mhmadalaa requested changes
Sorry, you didn't get me right
i mean that the entire content of readme description need a little clarifications that it's the backend part
![image](https://github.com/lilhind/bookipedia/assets/68995755/8aa73251-1a6f-4e71-aaf0-d4ed8d4ceec5)

2024-01-08 21:56 UTC, lilhind commented
commit & push to `readme` branch

2024-01-10 11:34 UTC, mhmadalaa approved these changes

2024-01-25 14:03 UTC, Nayra000 approved these changes

2024-01-25 14:03 UTC, merged